---
- name: Update APT
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: Install APT Requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "nginx"

- name: Copy config template
  template:
    src: nginx_ansible-container.conf
    dest: /etc/nginx/nginx_ansible-container.conf
    